### PR TITLE
Add Simple History, as it also is a logger-ish plugin

### PR DESCRIPTION
**Pull request by bonny**

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@bonny Can you please (a) fix the merge conflict by doing a rebase on the latest merges and (b) link to the plugins source on GitHub? You can link to the dedicated page in the same line, but the first link must always link to the source as you can read at the top of the README and is what you see in all other examples. Thanks in advance.

**Comment by bonny** [comment]
Done a rebase and changed the link. Let me know if it looks ok or not!

**Comment by franz-josef-kaiser** [comment]
@bonny Looking good. Thanks, mate!

**Comment by franz-josef-kaiser** [comment]
For the books: Wrong green button previously …

**Pull request merged**
