### PR TITLE
Add wp-scratch-box

### PR DESCRIPTION
**Pull request by cristovaov**
Hi, I'd like to submit my project to WP-Gear. I believe it to be a valuable tool in certain setups as the ones mentionned in the description. Thank you kindly.

### CODE REVIEW

**Comment by cristovaov** [comment]
Hi there, I saw that my PR has been open for a while. Can you tell me what my project lacks for inclusion on WPGear?

**Comment by franz-josef-kaiser** [comment]
@cristovaov the main reason is that I had to open the PR, copy/paste the link, read through your `README.md` etc. and stopped half the way down the road as I had no time for it at the moment(s) I got on it. The description in the PR does not explain what it is about and the commit message is the exact same message. When I finally got on it, it says "Alpha" and I don't want to add _alpha_ state releases. I will leave the PR open until you have reached RC or later state. Just ping me for an update then. Does that work for you?

**Comment by cristovaov** [comment]
Yes, it certainly works for me. It would have been helpful to me had you mentionned this when I submitted, though. I could have edited my comment and make the necessary adjustments. Thanks and till the ping!

**Comment by franz-josef-kaiser** [comment]
@cristovaov Agree that it would have been helpful. I really need to add pull request templates and contribution guidelines now that GitHub enables it. Thanks for your patience tough.

**Comment by cristovaov** [comment]
Ping @franz-josef-kaiser 

With my latest commits I have dropped the alpha on `wp-scratch-box`. Please find below a summary of what the project is about:

`wp-scratch-box` is a Vagrant configuration for WordPress. With a provisioning around the +/- 5 minutes mark, it is particularly useful for presentations and workshops where all you need is a default WP install. Configurable through its JSON file, it usefullness extends to minor development. With its support for Vagrants' Multi-Machine, `wp-scratch-box` can serve as a local staging environment to more developer centric Vagrant configs such as VVV and others.

**Comment by franz-josef-kaiser** [comment]
@cristovaov merged. You might want to tag that version in Git and push that upstream.

**Comment by cristovaov** [comment]
Thank you. I'll tag the version on my repo as you recommend.

**Pull request merged**
