### PR TITLE
Add the GenerateWP website

### PR DESCRIPTION
**Pull request by jrfnl**
Website which will generate the code for adding taxonomies, post types, sidebars, menus, shortcodes, queries, cron jobs and much more.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Still not sure what to do with this one. I agree it's helpful for test cases, but I am afraid people would start copying to production from there.

**Comment by jrfnl** [comment]
Who are we to decide how people use the tools ?
GenerateWP generates valid code and for some cases, copy/pasting that code straight to production might well be valid.
However, as WP Gear is more aimed at developers, I suspect, most visitors would use it to get a quick starting point from which to continue their own coding.

It's also a useful tool for learning the parameters of common functions to build onto WP and to avoid copy/pasting your own code from previous projects and missing new parameters ;-)

**Comment by franz-josef-kaiser** [comment]
> Who are we to decide how people use the tools?

Providing such a list also means _recommending_ things. Without clear notice or disclaimers it might be misleading.

> It's also a useful tool for learning the parameters of common functions to build onto WP and to avoid copy/pasting your own code from previous projects and missing new parameters ;-)

That I agree on, so it's merged.

Still, I am thinking about removing all appearances of _Advanced Custom Fields_ as it drives people into migration hell and messes up databases like nothing else, while being widely spread.

**Comment by jrfnl** [comment]
I'm personally not a fan of ACF - especially not after having found CMB2 -, however, depending on the experience level of the developer and/or for specific use cases, I can see why people would still choose to use it.

For me personally, I see WP Gear not so much as recommendations as, as a great way to discover interesting, development focused, tooling in the WP ecosphere.

As lot of it is fragmented all over the web, WP Gear is a great way to discover what's out there and - depending on need and use-case, to decide what to use.

Just my two pennies.

**Pull request merged**
