### PR TITLE
Open Source Codestar framework added

### PR DESCRIPTION
**Pull request by mayeenulislam**
A Lightweight and easy-to-use WordPress Options Framework

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@mayeenulislam Sorry, but this is mostly an advertising site for that companies _Themeforest_ themes. Even with the [direct code source](https://github.com/Codestar/codestar-framework/), there's advertising in the README. Not that this would make it a total show stopper, but there should be some reason that makes it worth adding it to the stack. Do you have tried it and can give some insights? Thanks in advance!

**Comment by mayeenulislam** [comment]
@franz-josef-kaiser Just take it as a suggestion. You keep all the rights adding things that's eligible.

Yes, I've used it. But not for all the cases, I used it only for Theme Options, in 3 of my live projects, and one of my github released WordPress theme. I can say that, as a theme options, I found it faster than most others, and it's nicer too. That's why [I tried supporting them](https://github.com/Codestar/codestar-framework/issues/213).

And I thought it could be on the list that's why I suggested. :)

**Comment by franz-josef-kaiser** [comment]
After thinking about it, I still have to file this as "commercial theme" … Thanks for your time tough!

**Comment by mayeenulislam** [comment]
:)

**Pull request closed without merging**
