### PR TITLE
added WP PHP Console in Debug tools and WP Requirements in boilerplates

### PR DESCRIPTION
**Pull request by nekojira**

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Could you please separate those per pull request? Also: The `WP Requirements` singleton does not have any sanitization (and it's not noted anywhere). Therefore it's unsafe and I won't move it in, sry. Please: Update.

**Comment by nekojira** [comment]
ok about separating the requests

could you elaborate a bit more where you found  WP Requirements not safe and why? (point the line in code please) - there is no database interaction, the class was inspired by a post appeared on the very own make.wordpress.org - all it does, you pass the version of php, version of wordpress you'd like to check against, if it's something `VERSION_COMPARE` can't understand it would fail the check and that's all

**Comment by franz-josef-kaiser** [comment]
Well, there's no _sanitization_, meaning that it returns whatever value is delivered. If I intercept a global and return something different, then we have a possible hack.

**Comment by nekojira** [comment]
ok I will replace $wp_version with get_bloginfo('version');

**Pull request closed without merging**
