### PR TITLE
Added WPBP

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Mte90** [comment]
any news?

**Comment by franz-josef-kaiser** [comment]
@Mte90 I simply didn't get what this actually is. It is a Vagrant machine, a fork of Toms plugin boilerplate, a Yeoman generator? Could you please add a bit of a description? Thanks.

**Comment by Mte90** [comment]
is a fork of toms plugin boilerplate with many improvements

**Comment by Mte90** [comment]
any news?

**Comment by franz-josef-kaiser** [comment]
> any news?

Yes, but it took me quite some time to actually review what it is, to take a look at it's code and to see what exactly the linked libraries (from your README*) are. While I am not really a fan of a library that highly opinionated (using the provided libraries without providing a facade to make them exchangeable), I understand that there might be people using it. So yes, it goes in.

_*) You have dead/ 404 links in your README_

**Comment by Mte90** [comment]
Thank you.

I've updated the readme with the fixed links.

**Pull request merged**
