### PR TITLE
Added SMTP URI

### PR DESCRIPTION
**Pull request by szepeviktor**
SMTP settings for WordPress and error logging.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@szepeviktor Do you have GitHub or Bitbucket repositories (and maybe with `composer.json`) files as well? Much easier to install and review. Thanks in advance!

**Comment by szepeviktor** [comment]
Of course https://github.com/szepeviktor/smtp-uri

**Comment by szepeviktor** [comment]
This plugin is too small to be a composer package.

**Comment by franz-josef-kaiser** [comment]
@szepeviktor Could you update both your repos to point to the GitHub sources? And everything should be a composer package. Nothing is too small. Composer is just a package manager to nail down versions and have a fast, easy and reliable (and sharable) update flow.

**Comment by szepeviktor** [comment]
Could you resolve this conflict?

**Comment by franz-josef-kaiser** [comment]
@szepeviktor Done with b289ccf

ProTip: There's always an explanation including problem resolving commands on bottom. When you look at the lines that say `CONFLICT` in the terminal/ command line, it's normally a very easy fix (which lines to take, which to drop).

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
