### PR TITLE
Add WPackagist website

### PR DESCRIPTION
**Pull request by jrfnl**

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@jrfnl Thanks for all your PRs. Please, add descriptions for your PRs, so it's easier to scan and review them. Thanks!

**Comment by jrfnl** [comment]
@franz-josef-kaiser You mean copy the description which is in the code change ? I've included descriptions in the actual changes. Why duplicate ?

**Comment by jrfnl** [comment]
Oh and for a few which touched more than one line, I did actually include a description already.

**Comment by franz-josef-kaiser** [comment]
> Why duplicate

As I maintain this site now since quite some time and as it is not the only project I maintain (in my spare time), it is much easier and faster for me to get around the PRs and saves me from clicking through all diffs to prioritize them. Also, a duplicate might not be the best option to describe what changed, better might be to just describe what the added/updated/removed link is about instead. Thanks.

**Comment by jrfnl** [comment]
> As I maintain this site now since quite some time and as it is not the only project I maintain (in my spare time), it is much easier and faster for me to get around the PRs and saves me from clicking through all diffs to prioritize them.

Yes and while I appreciate that, you are not the only one donating time, after all, I've been creating the updates in *my* spare time while this is not the only project I contribute to either....

> Also, a duplicate might not be the best option to describe what changed, better might be to just describe what the added/updated/removed link is about instead. Thanks.

That *would* be duplicating the information as that is exactly what is in the link description/commit message already. If there were more extensive changes, I did already include a description in the PR.

**Comment by jrfnl** [comment]
@franz-josef-kaiser Well as there is no movement on the open PRs, I've been so kind as to spend even more of my time on the project and done the copy & pasting so *you* don't have to click through to the code tab.... All my PRs now contain a description of sorts.

**Pull request merged**
