### PR TITLE
Clean up and update "PHP bits"

### PR DESCRIPTION
**Pull request by MikeNGarrett**
Corrected redirected or broken urls.
Corrected spelling mistakes.
Added 'last updated' messages for abandoned code.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@MikeNGarrett first, thanks a lot for the effort you have put into this PR! Could you please remove the "last updated" note from those lines before we are merging this? The "arms race" promoted by w.org and _Automattic_ when it comes to updates is something that imo makes no sense at all. There are plenty of perfectly working, not updated since ages, plugins out there and I really don't want to port this idea to this still sane place. I hope you understand that reason and can agree on it. Thanks in advance!

**Comment by MikeNGarrett** [comment]
Ok, I understand. I'll remove it. I think it's useful to developers to see what's potentially abandoned.

**Comment by MikeNGarrett** [comment]
Updated.

**Comment by franz-josef-kaiser** [comment]
@MikeNGarrett Thanks for your PR and the update. Sorry that it took that long.

**Comment by MikeNGarrett** [comment]
Not a problem. Glad I could help.

**Pull request merged**
